ERROR:root:get_latest_github_version: Error fetching latest release: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/phoenixthrush/AniWorld-Downloader/releases/latest (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fff30e07ad0>, 'Connection to api.github.com timed out. (connect timeout=30)'))
Traceback (most recent call last):
  File "/usr/local/bin/aniworld", line 3, in <module>
    from aniworld.__main__ import main
  File "/app/src/aniworld/__main__.py", line 9, in <module>
    from .entry import aniworld
  File "/app/src/aniworld/entry.py", line 81, in <module>
    def _group_episodes_by_series(links: List[str]) -> List[Union[Anime, Movie]]:
                                                            ^^^^^
NameError: name 'Union' is not defined
ERROR:root:get_latest_github_version: Error fetching latest release: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/phoenixthrush/AniWorld-Downloader/releases/latest (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fff0ca2f9e0>: Failed to resolve 'api.github.com' ([Errno -3] Temporary failure in name resolution)"))
Traceback (most recent call last):
  File "/usr/local/bin/aniworld", line 3, in <module>
    from aniworld.__main__ import main
  File "/app/src/aniworld/__main__.py", line 9, in <module>
    from .entry import aniworld
  File "/app/src/aniworld/entry.py", line 81, in <module>
    def _group_episodes_by_series(links: List[str]) -> List[Union[Anime, Movie]]:
                                                            ^^^^^
NameError: name 'Union' is not defined
ERROR:root:get_latest_github_version: Error fetching latest release: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/phoenixthrush/AniWorld-Downloader/releases/latest (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fff811df830>: Failed to resolve 'api.github.com' ([Errno -3] Temporary failure in name resolution)"))
Traceback (most recent call last):
  File "/usr/local/bin/aniworld", line 3, in <module>
    from aniworld.__main__ import main
  File "/app/src/aniworld/__main__.py", line 9, in <module>
    from .entry import aniworld
  File "/app/src/aniworld/entry.py", line 81, in <module>
    def _group_episodes_by_series(links: List[str]) -> List[Union[Anime, Movie]]:
                                                            ^^^^^
NameError: name 'Union' is not defined
ERROR:root:get_latest_github_version: Error fetching latest release: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/phoenixthrush/AniWorld-Downloader/releases/latest (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fffae1ff8c0>: Failed to resolve 'api.github.com' ([Errno -3] Temporary failure in name resolution)"))
Traceback (most recent call last):
  File "/usr/local/bin/aniworld", line 3, in <module>
    from aniworld.__main__ import main
  File "/app/src/aniworld/__main__.py", line 9, in <module>
    from .entry import aniworld
  File "/app/src/aniworld/entry.py", line 81, in <module>
    def _group_episodes_by_series(links: List[str]) -> List[Union[Anime, Movie]]:
                                                            ^^^^^
NameError: name 'Union' is not defined
ERROR:root:get_latest_github_version: Error fetching latest release: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/phoenixthrush/AniWorld-Downloader/releases/latest (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fff14f06ea0>: Failed to resolve 'api.github.com' ([Errno -3] Temporary failure in name resolution)"))
Traceback (most recent call last):
  File "/usr/local/bin/aniworld", line 3, in <module>
    from aniworld.__main__ import main
  File "/app/src/aniworld/__main__.py", line 9, in <module>
    from .entry import aniworld
  File "/app/src/aniworld/entry.py", line 81, in <module>
    def _group_episodes_by_series(links: List[str]) -> List[Union[Anime, Movie]]:
                                                            ^^^^^
NameError: name 'Union' is not defined
ERROR:root:get_latest_github_version: Error fetching latest release: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/phoenixthrush/AniWorld-Downloader/releases/latest (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fff910d7b30>: Failed to resolve 'api.github.com' ([Errno -3] Temporary failure in name resolution)"))
Traceback (most recent call last):
  File "/usr/local/bin/aniworld", line 3, in <module>
    from aniworld.__main__ import main
  File "/app/src/aniworld/__main__.py", line 9, in <module>
    from .entry import aniworld
  File "/app/src/aniworld/entry.py", line 81, in <module>
    def _group_episodes_by_series(links: List[str]) -> List[Union[Anime, Movie]]:
                                                            ^^^^^
NameError: name 'Union' is not defined
ERROR:root:get_latest_github_version: Error fetching latest release: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/phoenixthrush/AniWorld-Downloader/releases/latest (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7ffef8ecf3b0>: Failed to resolve 'api.github.com' ([Errno -3] Temporary failure in name resolution)"))
Traceback (most recent call last):
  File "/usr/local/bin/aniworld", line 3, in <module>
    from aniworld.__main__ import main
  File "/app/src/aniworld/__main__.py", line 9, in <module>
    from .entry import aniworld
  File "/app/src/aniworld/entry.py", line 81, in <module>
    def _group_episodes_by_series(links: List[str]) -> List[Union[Anime, Movie]]:
                                                            ^^^^^
NameError: name 'Union' is not defined
ERROR:root:get_latest_github_version: Error fetching latest release: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/phoenixthrush/AniWorld-Downloader/releases/latest (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fff862bde50>: Failed to resolve 'api.github.com' ([Errno -3] Temporary failure in name resolution)"))
Traceback (most recent call last):
  File "/usr/local/bin/aniworld", line 3, in <module>
    from aniworld.__main__ import main
  File "/app/src/aniworld/__main__.py", line 9, in <module>
    from .entry import aniworld
  File "/app/src/aniworld/entry.py", line 81, in <module>
    def _group_episodes_by_series(links: List[str]) -> List[Union[Anime, Movie]]:
                                                            ^^^^^
NameError: name 'Union' is not defined
ERROR:root:get_latest_github_version: Error fetching latest release: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/phoenixthrush/AniWorld-Downloader/releases/latest (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fff033d7f20>: Failed to resolve 'api.github.com' ([Errno -3] Temporary failure in name resolution)"))
Traceback (most recent call last):
  File "/usr/local/bin/aniworld", line 3, in <module>
    from aniworld.__main__ import main
  File "/app/src/aniworld/__main__.py", line 9, in <module>
    from .entry import aniworld
  File "/app/src/aniworld/entry.py", line 81, in <module>
    def _group_episodes_by_series(links: List[str]) -> List[Union[Anime, Movie]]:
                                                            ^^^^^
NameError: name 'Union' is not defined
Traceback (most recent call last):
  File "/usr/local/bin/aniworld", line 3, in <module>
    from aniworld.__main__ import main
  File "/app/src/aniworld/__main__.py", line 9, in <module>
    from .entry import aniworld
  File "/app/src/aniworld/entry.py", line 81, in <module>
    def _group_episodes_by_series(links: List[str]) -> List[Union[Anime, Movie]]:
                                                            ^^^^^
NameError: name 'Union' is not defined
